# Generated by Django 5.0.8 on 2024-08-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('subscriptions', '0002_subscriptions_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='permissions',
            field=models.ManyToManyField(limit_choices_to={'codename__in': ['basic', 'pro', 'advanced'], 'content_type__app_label': 'subscriptions'}, to='auth.permission'),
        ),
    ]
